AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs22.x

  Sample SAM Template for lambda-nodejs22.x

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: ping.handler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Events:
        Ping:
          Type: Api
          Properties:
            Path: /ping
            Method: get

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: auth/register.handler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Events:
        Register:
          Type: Api
          Properties:
            Path: /auth/register
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PingApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/ping/'
  PingFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt PingFunction.Arn
  PingFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt PingFunctionRole.Arn

  RegisterApi:
    Description: 'API Gateway endpoint URL for Prod stage for Register function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/auth/register/'
  RegisterFunction:
    Description: 'Register Lambda Function ARN'
    Value: !GetAtt RegisterFunction.Arn
  RegisterFunctionIamRole:
    Description: 'Implicit IAM Role created for Register function'
    Value: !GetAtt RegisterFunctionRole.Arn
